[package]
name = "entitydata"
version = "0.1.0"
authors = ["ganmin <jxz_211@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
